stages:
  - build
  - test
  - deploy
  - release

include:
  - project: fabnum-minarm/igloo/gitlab-templates
    file: 
      - /proxy/licence-scanning.yml
      - /proxy/dependency-scanning.yml
      - /proxy/container-scanning.yml
      - /proxy/secret-scanning.yml
      - /proxy/sast.yml
      - /npm.auto.yml
      - /docker.auto.yml
      - /helm.yml
      - /helm.reviews.auto.yml
      - /helm.staging.auto.yml
      - /helm.production.auto.yml

variables:
  HELM_CHART: igloo-stable/nodejs
  HELM_ENV_VAR_VERSION: Version ${CI_COMMIT_REF_NAME} - ${CI_COMMIT_SHA} (job \#${CI_JOB_ID})
  GENERIC_PACKAGE_NAME: stargate_frontend

deploy:review:
  variables:
    HOST: ${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_NAME: frontend-${CI_COMMIT_REF_SLUG}
    HELM_ENV_VAR_API_URL: https://api.${BASE_DOMAIN}/api
  environment:
    url: https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}

deploy:review:uninstall:
  variables:
    HELM_NAME: frontend-${CI_COMMIT_REF_SLUG}

deploy:staging:
  variables:
    HOST: ${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_ENV_VAR_API_URL: https://api.${BASE_DOMAIN}/api
    HELM_NAME: frontend
  environment:
    url: https://${BASE_DOMAIN}

deploy:staging:uninstall:
  variables:
    HELM_NAME: frontend

deploy:production:
  variables:
    HOST: ${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_ENV_VAR_API_URL: https://api.${BASE_DOMAIN}/api
    HELM_NAME: frontend
  environment:
    url: https://${BASE_DOMAIN}

deploy:production:uninstall:
  variables:
    HELM_NAME: frontend

pages:
  extends: .igloo:npm:pages-docs
