stages:
  - test
  - build
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

variables:
  DS_DISABLE_DIND: "true"

.deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.0.3
  variables:
    KUBECONFIG: /etc/deploy/config
    K8S_CLUSTER_NAME: current
  before_script:
    - mkdir -p `dirname $KUBECONFIG`
    - touch $KUBECONFIG
    - kubectl config set-cluster ${K8S_CLUSTER_NAME} --server="${K8S_HOST}"
    - kubectl config set clusters.${K8S_CLUSTER_NAME}.certificate-authority-data "${K8S_CA}"
    - kubectl config set-credentials ${K8S_USER} --token="${K8S_TOKEN}"
    - kubectl config set-context ${K8S_NAMESPACE} --cluster="${K8S_CLUSTER_NAME}" --user="${K8S_USER}" --namespace="${K8S_NAMESPACE}"
    - kubectl config use-context ${K8S_NAMESPACE}
  script:
    - helm upgrade
      --install
      --namespace ${K8S_NAMESPACE}
      --set image.tag="${CI_COMMIT_REF_SLUG}"
      --set ingress.enabled=true
      --set ingress.host="${DEPLOYMENT_HOST}"
      --set imageCredentials.username="${DOCKER_REGISTRY_USER}"
      --set imageCredentials.password="${DOCKER_REGISTRY_PASSWORD}"
      --set imageCredentials.registry="${CI_REGISTRY}"
      --set env.API_URL="${API_URL}"
      --set env.VERSION="Version ${CI_COMMIT_REF_NAME} - ${CI_COMMIT_SHA} (job \#${CI_JOB_ID})"
      --wait
      ${HELM_NAME}
      .helm-chart

.node:
  image: node:alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm install

retire-js-dependency_scanning:
  only:
    changes:
      - package-lock.json
gemnasium-dependency_scanning:
  only:
    changes:
      - package-lock.json
license_management:
  only:
    changes:
      - package-lock.json

lint:
  stage: test
  extends: .node
  script:
    - npm run lint

test:
  stage: test
  extends: .node
  script:
    - npm run test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.17.1
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy_review:
  extends: .deploy
  variables:
    K8S_USER: ${K8S_DEV_USER}
    K8S_TOKEN: ${K8S_DEV_TOKEN}
    K8S_NAMESPACE: ${K8S_DEV_NAMESPACE}
    DEPLOYMENT_HOST: ${CI_COMMIT_REF_SLUG}.${STAGING_DOMAIN}
    API_URL: ${STAGING_API_URL}
    HELM_NAME: frontend-${CI_COMMIT_REF_SLUG}
  except:
    refs:
      - tags
      - master
      - develop

deploy_staging:
  extends: .deploy
  variables:
    K8S_USER: ${K8S_STAGING_USER}
    K8S_TOKEN: ${K8S_STAGING_TOKEN}
    K8S_NAMESPACE: ${K8S_STAGING_NAMESPACE}
    DEPLOYMENT_HOST: ${STAGING_DOMAIN}
    API_URL: ${STAGING_API_URL}
    HELM_NAME: frontend
  only:
    refs:
      - develop
