# Default values for next.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/fabnum-minarm/stargate/frontend
  pullPolicy: Always

monitoring:
  exporter:
    enabled: true
    port: 9091
  dashboard:
    deploy: true
    sidecarLabel: grafana-dashboard

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}


imageCredentials:
  registry: registry.gitlab.com
  username: user
  password: pass

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  host: localhost
  issuer: letsencrypt-silentprod

env:
  VERSION: null
  API_URL: null

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
