{{- if .Values.ingress.enabled -}}
{{- $fullName := include "next.fullname" . -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $fullName }}
spec:
  secretName: {{ $fullName }}-tls
  issuerRef:
    name: {{ .Values.ingress.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host | quote }}
  dnsNames:
    - {{ .Values.ingress.host | quote }}
{{- end}}