{{- if .Values.ingress.enabled -}}
{{- $fullName := include "next.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "next.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  tls:
    - secretName: {{ $fullName }}-tls
      hosts:
      - {{ .Values.ingress.host | quote }}
{{- end -}}