apiVersion: v1
kind: Service
metadata:
  name: {{ include "next.fullname" . }}
  labels:
    {{- include "next.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.monitoring.exporter.enabled }}
    - port: {{ .Values.monitoring.exporter.port }}
      targetPort: {{ .Values.monitoring.exporter.port }}
      protocol: TCP
      name: metrics
{{- end }}
  selector:
    {{- include "next.selectorLabels" . | nindent 4 }}
