export const REQUEST_OBJECT = {
  PRIVATE: 'PRIVATE',
  PROFESSIONAL: 'PROFESSIONAL',
};

export const ROLES = {
  ROLE_SUPERADMIN: 'ROLE_SUPERADMIN',
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_UNIT_CORRESPONDENT: 'ROLE_UNIT_CORRESPONDENT',
  ROLE_SECURITY_OFFICER: 'ROLE_SECURITY_OFFICER',
  ROLE_ACCESS_OFFICE: 'ROLE_ACCESS_OFFICE',
  ROLE_SCREENING: 'ROLE_SCREENING',
  ROLE_HOST: 'ROLE_HOST',
  ROLE_OBSERVER: 'ROLE_OBSERVER',
};

export const ID_DOCUMENT = {
  IDCARD: 'IDCard',
  PASSPORT: 'Passport',
  CIMSCARD: 'CIMSCard',
};
