name: SAST analysis

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '21 22 * * 3'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: '0'
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master

  codeql:
    name: Analyze
    runs-on: ubuntu-latest
#    runs-on: self-hosted

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
#        uses: synced-actions/github-codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
#        uses: synced-actions/github-codeql-action/analyze@v1
        uses: github/codeql-action/analyze@v1
